# This is a basic workflow to help you get started with Actions

name: 'Update Version'

# Controls when the action will run. 
on:
  release:
    types: [ released ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      - name: Update version.txt version
        run: echo '${{ github.event.release.tag_name }}' > CompilePalX/version.txt
          
      - name: Update version.txt on GitHub
        uses: test-room-7/action-update-file@v1.4.0
        with:
            file-path: CompilePalX/version.txt
            commit-msg: Update version
            github-token: ${{ secrets.GITHUB_TOKEN }}
